using UnityEngine;
using UnityEngine.UI;
using System.Collections.Generic;

public class EnvironmentsScreen : MonoBehaviour
{
  public static EnvironmentsScreen Instance;

  [Header("Environment Card Setup")]
  [SerializeField] private GameObject environmentCardPrefab;
  [SerializeField] private Transform cardsContainer;

  [Header("Next Screen")]
  [SerializeField] private GameObject levelsScreenPrefab;

  [System.Serializable]
  public class EnvironmentData
  {
    public Sprite environmentSprite;
    public string environmentName;
    public bool isLocked;
  }

  [Header("Environments Data")]
  [SerializeField] private List<EnvironmentData> environments = new List<EnvironmentData>();

  private void Awake()
  {
    Instance = this;
  }

  private void Start()
  {
    ScreenTheme.ApplyListScreen(transform, null);
    DimBackdrop();
    CentreCards();
    PopulateEnvironmentCards();

    // Start on Environment 1. The content has to be laid out first — setting
    // the scroll position before the size fitter has run leaves the row parked
    // half a card left of the viewport.
    var scroll = GetComponentInChildren<ScrollRect>(true);
    if (scroll != null)
    {
      Canvas.ForceUpdateCanvases();
      if (scroll.content != null) LayoutRebuilder.ForceRebuildLayoutImmediate(scroll.content);
      scroll.vertical = false;   // a horizontal strip should not drift vertically

      // Positioned directly rather than via horizontalNormalizedPosition: the
      // content is anchored left with a left pivot, so zero already means "left
      // edge against the viewport", and the normalised form kept landing a
      // fraction of a card short.
      if (scroll.content != null)
      {
        scroll.content.anchoredPosition = new Vector2(0f, scroll.content.anchoredPosition.y);
      }
      // The bar tracks the content, and is not updated by moving the rect
      if (scroll.horizontalScrollbar != null) scroll.horizontalScrollbar.value = 0f;
    }

    ScreenFade.In(transform);
  }

  // Darkens the menu art so the cards read as the foreground. Done by tinting
  // the background image itself rather than adding an overlay object, which the
  // prefab's own draw order kept swallowing.
  private void DimBackdrop()
  {
    foreach (Transform child in GetComponentsInChildren<Transform>(true))
    {
      if (child.name != "Background") continue;

      var image = child.GetComponent<Image>();
      if (image != null) image.color = new Color(0.42f, 0.46f, 0.54f, 1f);
      return;
    }
  }

  // Card art comes from Resources/EnvPreviews/<environment name>, generated by
  // CameraPreview.RenderEnvironmentCards.
  //
  // The inspector's environmentSprite is deliberately ignored: every one of the
  // seven entries points at the same grey placeholder, so using it made every
  // card identical and made environments with no art look broken rather than
  // simply locked. Drop a PNG into that folder to supply custom art.
  private static Sprite ResolvePreview(EnvironmentData envData)
  {
    return Resources.Load<Sprite>("EnvPreviews/" + envData.environmentName);
  }

  // Left-aligned, not centred: there are seven environments, so the strip is
  // wider than the screen and centring pushed the first two off the left edge.
  // It starts at the left and scrolls right.
  private void CentreCards()
  {
    var content = cardsContainer as RectTransform;
    if (content == null) return;

    content.anchorMin = new Vector2(0f, 0.5f);
    content.anchorMax = new Vector2(0f, 0.5f);
    content.pivot = new Vector2(0f, 0.5f);
    content.anchoredPosition = Vector2.zero;

    // Cards were nearly half the screen tall. Let the row drive their size so
    // several fit at once and the art reads as a set of thumbnails.
    var row = content.GetComponent<HorizontalLayoutGroup>();
    if (row != null)
    {
      row.spacing = 30f;
      row.padding = new RectOffset(48, 48, 0, 0);
      row.childAlignment = TextAnchor.MiddleLeft;
      // The group drives both axes from each card's LayoutElement; with control
      // off, the prefab's own stretched rect won and the cards filled the screen.
      row.childControlWidth = true;
      row.childControlHeight = true;
      row.childForceExpandWidth = false;
      row.childForceExpandHeight = false;
      row.reverseArrangement = false;
    }

    var fitter = content.GetComponent<ContentSizeFitter>();
    if (fitter == null) fitter = content.gameObject.AddComponent<ContentSizeFitter>();
    fitter.horizontalFit = ContentSizeFitter.FitMode.PreferredSize;
    fitter.verticalFit = ContentSizeFitter.FitMode.Unconstrained;

    // The prefab's scroll view starts left of the screen edge, so the content —
    // anchored to it — dragged the first card half off-screen. Frame the view
    // to the screen, under the title.
    var scroll = content.GetComponentInParent<ScrollRect>();
    if (scroll != null)
    {
      var view = (RectTransform)scroll.transform;
      view.anchorMin = Vector2.zero;
      view.anchorMax = Vector2.one;
      view.pivot = new Vector2(0.5f, 0.5f);
      view.offsetMin = new Vector2(0f, 70f);
      view.offsetMax = new Vector2(0f, -190f);
    }
  }

  private void PopulateEnvironmentCards()
  {
    foreach (var envData in environments)
    {
      // Never enable an environment with no levels yet (would open an empty list)
      bool hasLevels = LevelRepository.GetLevelsForEnvironment(envData.environmentName).Count > 0;
      bool isLocked = !hasLevels || (envData.isLocked && !LevelProgress.UnlockAll);

      GameObject cardGO = Instantiate(environmentCardPrefab, cardsContainer);
      EnvironmentCard card = cardGO.GetComponent<EnvironmentCard>();
      if (card != null)
      {
        card.Setup(ResolvePreview(envData), envData.environmentName, isLocked);
      }

      Button cardButton = cardGO.GetComponent<Button>();
      if (cardButton != null)
      {
        string envName = envData.environmentName;
        cardButton.onClick.AddListener(() => OnEnvironmentSelected(envName));
        if (isLocked)
        {
          cardButton.interactable = false;
        }
      }
    }
  }

  public void SetLevelSelectionPrefab(GameObject prefab)
  {
    levelsScreenPrefab = prefab;
  }

  private void OnEnvironmentSelected(string environmentName)
  {
    Debug.Log("Selected Environment: " + environmentName);
    GameSession.SelectedEnvironment = environmentName;
    AudioManager.Instance?.PlaySound(AudioManager.SoundType.EnvironmentPicked);
    if (levelsScreenPrefab != null)
    {
      Instantiate(levelsScreenPrefab, transform.parent);
    }
    gameObject.SetActive(false);
  }
}
